title: SerialSeb
name: SerialSeb
description: SerialSeb
safe: true
lsi: false
highlighter: rouge
locale: en_GB
lang: en-gb
url: http://serialseb.com
timezone: Europe/London
kramdown:
   syntax_highlighter: rouge

#jekyll config
permalink: /blog/:year/:month/:day/:title/
sass:
  sass_dir: _sass
  style: compressed

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
whitelist:
  - jekyll-redirect-from

rest_kickstarter_url: http://www.kickstarter.com/projects/serialseb/practical-rest-building-hypermedia-systems
toplinks:
    - url: http://www.kickstarter.com/projects/serialseb/practical-rest-building-hypermedia-systems
      title: Buy "Practical ReST"
    - url: http://serialseb.com
      title: SerialSeb
    - url: http://openrasta.org
      title: OpenRasta
    - url: http://openwrap.org
      title: OpenWrap
leftlinks:
    - url: /
      title: Home
    - url: http://codebetter.com/sebastienlambla/
      title: Blog
    - url: /bio/index.html
      title: Bio
    - url: /rest/
      title: Practical ReST
    - url: /speaker/
      title: Speaker
    - url: /media/
      title: Media pack
    - url: /testimonials.html
      title: Testimonials
author:
  name: Sebastien Lambla
  email: seb@serialseb.com
  about: http://serialseb.com/about
# Site owner
owner:
  id: http://serialseb.com/#me
  url: http://serialseb.com/about/
  name: Sebastien Lambla
  avatar: bio-seb.jpg
  bio: "Passionately distributed systems, continuously improving."
  email: seb@serialseb.com
  disqus-shortname: codebetterblog
  google:
    analytics: UA-39783963-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  amazon: seri005-21
  social:
    feed: http://feeds.feedburner.com/SerialSeb
    email: seb@serialseb.com
    twitter: serialseb
    linkedin: serialseb
    facebook: serialseb
    google-plus: Serialseb
    github: serialseb
    stackoverflow: 2593/serialseb
    xing: #username
    instagram: serialseb
    lastfm: #username
    tumblr: realSerialSeb
    pinterest: SerialSeb
    foursquare: serialseb
    steam: #username
    dribbble: #username
    youtube: serialseb2
    soundcloud: #username
    weibo: #username
    flickr: #username
    codepen: #username
    vimeo: 5750409
    reddit: realSerialSeb

paginate: 3
paginate_path: "/blog/page:num"
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: serials
    values:
      layout: serial
  - scope:
      path: ""
      type: tag_pages
    values:
      layout: tag
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      active: true
      comments: true
      type: talk

collections:
  projects:
    permalink: /projects/:id/
  serials:
    output: true
    permalink: /serials/:name/
  tag_pages:
    output: true
    permalink: /tags/:path/
  talks:
    output: true
    permalink: /speaker/:path/
